[package]
name = "executor"
version = "0.1.0"
edition = "2018"

[dependencies]
eyre = "0.6.5"
futures = "0.3.16"
regex = "1.5.4"
telegram-bot = "0.8.0"
tempfile = "3.2.0"
tokio = { version = "0.2", features = ["full"] }
